version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  test_large:
    macos:
      xcode: 13.0.0
    resource_class: large
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec fastlane unit_test

  test_metal:
    macos:
      xcode: 13.0.0
    resource_class: metal
    steps:
      - checkout
      - ruby/install-deps:
          key: metal
      - run: bundle exec fastlane unit_test

workflows:
  test:
    jobs:
      - test_large
      - test_metal
