version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  test:
    macos:
      xcode: 13.1.0
    resource_class: macos.x86.large.gen2
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec fastlane unit_test

workflows:
  test:
    jobs:
      - test
