version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  unit_test:
    macos:
      xcode: 13.1.0
    # Resource class
    resource_class: large
    steps:
      - checkout
      # Ruby Orb(Install fastlane)
      - ruby/install-deps
      - run: bundle exec fastlane unit_test
      # Store Test Results
      - store_test_results:
          path: fastlane/test_report/report.junit

workflows:
  test:
    jobs:
      - unit_test
